sudo: 'required'

services:
  - 'docker'

notifications:
  email: false

env:
  global:
    - DOCKER_TAG=0.1.${TRAVIS_BUILD_NUMBER}
    - DOCKER_PUSH=1 # if DOCKER_PUSH is defined, `make docker-*` uploads images to dockerhub.
before_script:
  - git config --global user.email webapp+travis@wire.com
  - git config --global user.name "Wire Travis CI"
  - mkdir -p temp
  - openssl aes-256-cbc -K $encrypted_59d15aeab93c_key -iv $encrypted_59d15aeab93c_iv -in services/brig/deb/opt/brig/bin/deploy.enc -out temp/deploy -d
  - chmod 600 temp/deploy
  - eval `ssh-agent -s`
  - ssh-add temp/deploy
  - rm -rf temp

script:
  - 'if ["$TRAVIS_PULL_REQUEST" != "false"]; then python services/brig/deb/opt/brig/bin/fetch.py; fi'

branches:
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - make ${TARGETS[@]}
  only:
    - develop
