sudo: 'required'

language: node_js
node_js:
  - '8'

cache: yarn

services:
  - 'docker'

env:
  global:
    - DOCKER_TAG=0.1.${TRAVIS_BUILD_NUMBER}
    - DOCKER_PUSH=1 # if DOCKER_PUSH is defined, `make docker-*` uploads images to dockerhub.
  matrix:
    - TARGETS="docker-deps"
    - TARGETS="docker-intermediate docker-migrations"
    - TARGETS="docker-intermediate
               docker-exe-api-loadtest
               docker-exe-api-smoketest
               docker-exe-bonanza
               docker-exe-brig
               docker-exe-brig-index
               docker-exe-brig-integration
               docker-exe-brig-schema
               docker-exe-cannon
               docker-exe-cargohold
               docker-exe-cargohold-integration
               docker-exe-galley
               docker-exe-galley-integration
               docker-exe-galley-journaler
               docker-exe-galley-schema
               docker-exe-gundeck
               docker-exe-gundeck-integration
               docker-exe-gundeck-schema
               docker-exe-kibana-raw
               docker-exe-kibanana
               docker-exe-makedeb
               docker-exe-metrics-collector
               docker-exe-proxy
               docker-exe-ropes-aws-auth-test
               docker-exe-ropes-aws-test
               docker-exe-zauth"

before_script:
  - git config --global user.email webapp+travis@wire.com
  - git config --global user.name "Wire Travis CI"
  - mkdir -p temp
  - openssl aes-256-cbc -K $encrypted_59d15aeab93c_key -iv $encrypted_59d15aeab93c_iv -in services/brig/deb/opt/brig/bin/deploy.enc -out temp/deploy -d
  - chmod 600 temp/deploy
  - eval `ssh-agent -s`
  - ssh-add temp/deploy
  - rm -rf temp

script:
  - 'if ["$TRAVIS_PULL_REQUEST" != "false"]; then python services/brig/deb/opt/brig/bin/fetch.py; fi'

notifications:
  email: false

deploy:
  provider: script
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - make ${TARGETS[@]}
  on:
    branch: develop
